### ISSUE TITLE
Publish binaries for 1.1.0 and update CF-Community metadata

### ISSUE THREAD

**Issue by shakuzen** [orange-cloudfoundry/cf-plugin-bg-restage#4]
The [release version 1.1.0 was made](https://github.com/orange-cloudfoundry/cf-plugin-bg-restage/releases/tag/v1.1.0) but the binaries are not available. Could you please publish the binaries on the releases page?

Once that has been done, could you update the metadata for [CF-Community](https://plugins.cloudfoundry.org/) so the 1.1.0 version of the plugin can be updated/installed from the CF CLI easily?

**Comment by ArthurHlt** [comment]
This has been released and request has been made (see https://github.com/cloudfoundry/cli-plugin-repo/pull/269 )
Thanks for the alert
